---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/members":
    get:
      summary: list members
      tags:
      - Members
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
    post:
      summary: create member
      responses:
        '200':
          description: successful
  "/members/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show member
      responses:
        '200':
          description: successful
    patch:
      summary: update member
      responses:
        '200':
          description: successful
    put:
      summary: update member
      responses:
        '200':
          description: successful
    delete:
      summary: delete member
      responses:
        '200':
          description: successful
  "/current_user":
    get:
      summary: current_user member
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
